# Generated by Django 4.1.5 on 2023-02-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(max_length=20)),
                ('image', models.ImageField(max_length=200, upload_to='')),
                ('release_date', models.DateField(max_length=20)),
                ('lte_exists', models.BooleanField(max_length=10)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
    ]
